const grid=document.getElementById('grid'),classEl=document.getElementById('class'),familiesEl=document.getElementById('families'),sortEl=document.getElementById('sort'),searchEl=document.getElementById('search'),crossEl=document.getElementById('cross'),paletteEl=document.getElementById('palette'),tip=document.getElementById('tip'),dekEl=document.getElementById('dek');
// The landing subtitle teaches the encoding in one line; a family or a cross-date replaces it (updateStatus).
const DEFAULT_DEK='Each ring is one calendar year. Wider means more growth, darker means more volatile, and a scar is a major crash. Click any tree for its full record.';
document.getElementById('retry-load').onclick=()=>location.reload();
let trees=[],insights,sort='curated',family='all',crossYear=null,palette='wood',raf=0;
function metric(t){return LivingTrees.metrics(t,9999)}
// Populate the arrange-by dropdown from the shared sort registry.
sortEl.innerHTML=Collection.SORT_ORDER.map(k=>`<option value="${k}">${Collection.SORTS[k].label}</option>`).join('');
function list(){return Collection.order(trees,insights,{sort,cls:classEl.value,family,q:searchEl.value})}
function focusedRing(t){return crossYear?t.rings.find(r=>r.year===crossYear):null}
function cardStats(t){const r=focusedRing(t);if(r)return `<b>${r.ret>=0?'+':''}${(r.ret*100).toFixed(1)}%</b> in ${crossYear}<br><b>${(r.vol*100).toFixed(1)}%</b> volatility`;const m=metric(t),sortValue=Collection.SORTS[sort].value(t);return sortValue?`<b>${sortValue}</b><br>${(m.worst*100).toFixed(1)}% worst DD`:`<b>${(m.cagr*100).toFixed(1)}%</b> CAGR<br><b>${(m.worst*100).toFixed(1)}%</b> worst DD`}
// Age-anchored disc radius. A tree's size on the wall is its age, measured against a
// FIXED 100-year reference — never against the oldest tree currently on screen, so
// adding an older specimen later cannot resize the whole collection. The 0.35 exponent
// is the compromise from the century-tuning study: enough compression that a 15-ring sapling
// still reads (~51% radius, rings legible) while a century elder is visibly the elder.
const AGE_REF_YEARS=100,AGE_EXP=.35;
function ageScale(t){return Math.min(1,Math.pow((t.n_rings||t.rings.length)/AGE_REF_YEARS,AGE_EXP))}
function paintOne(cv){const t=trees.find(x=>x.id===cv.dataset.id),s=cv.clientWidth,dpr=Math.min(devicePixelRatio||1,1.6);cv.style.height=s+'px';cv.width=Math.round(s*dpr);cv.height=Math.round(s*dpr);const g=cv.getContext('2d');g.setTransform(dpr,0,0,dpr,0,0);g.clearRect(0,0,s,s);cv._size=s;cv._geo=LivingTrees.drawDetailedRings(g,t,s/2,s/2,s*.42*ageScale(t),9999,{palette,years:false,focusYear:crossYear,highlightYear:cv._hoverYear||crossYear})}
function paint(){cancelAnimationFrame(raf);raf=requestAnimationFrame(()=>document.querySelectorAll('.specimen canvas').forEach(paintOne))}
function animateFrom(first){requestAnimationFrame(()=>document.querySelectorAll('.specimen').forEach(card=>{const old=first.get(card.dataset.id);if(!old)return;const now=card.getBoundingClientRect(),dx=old.left-now.left,dy=old.top-now.top;if(Math.abs(dx)>1||Math.abs(dy)>1)card.animate([{transform:`translate(${dx}px,${dy}px)`},{transform:'translate(0,0)'}],{duration:520,easing:'cubic-bezier(.2,.75,.25,1)'})}))}
// The visible count lives in the headline (whole collection) or the subtitle (a family),
// not in a separate status line that would restate the highlighted family button.
function composeHeadline(n){if(family==='all'&&sort==='curated')return `A living collection of ${n} financial histories`;const subject=family==='all'?`${n} specimens`:TreeInsights.FAMILY_LABELS[family];return sort==='curated'?subject:`${subject}, ${Collection.SORTS[sort].headline}`}
function updateStatus(shown){if(crossYear){const rings=shown.map(focusedRing).filter(Boolean),negative=rings.filter(r=>r.ret<0).length,scarred=shown.filter(t=>(t.scars||[]).some(s=>s.year===crossYear)).length;document.getElementById('headline').textContent=`${crossYear} scarred ${scarred} of ${rings.length} visible trees`;dekEl.textContent=`Cross-dating ${crossYear} across every visible specimen — same calendar angle, so a market-wide event carves at the same clock position on every tree. ${negative} negative years · ${scarred} qualifying scars.`}else{document.getElementById('headline').textContent=composeHeadline(shown.length);dekEl.textContent=family==='all'?DEFAULT_DEK:`${TreeInsights.FAMILY_COPY[family]} ${shown.length} specimens.`}}
function render(animate=true){const first=new Map([...document.querySelectorAll('.specimen')].map(el=>[el.dataset.id,el.getBoundingClientRect()]));const shown=list(),ranked=sort!=='curated';grid.innerHTML=shown.map((t,i)=>{const m=metric(t),fam=TreeInsights.familyOf(insights,t);return `<article class="specimen" data-id="${t.id}" tabindex="0" role="link" aria-label="Open ${t.name}, ${t.id.toUpperCase()}, with ${m.years} annual rings">${ranked?`<span class="rank">#${i+1}</span>`:''}<canvas data-id="${t.id}" aria-hidden="true"></canvas><div class="caption"><div><div class="name" style="color:${LivingTrees.CLASS_COLORS[t.cls]}">${t.name}</div><div class="class"><b>${t.id.toUpperCase()}</b> · ${LivingTrees.CLASS_NAMES[t.cls]} · ${TreeInsights.FAMILY_LABELS[fam]}</div><div class="class">${t.first_year}–${t.last_year} · ${m.years} rings</div></div><div class="stats">${cardStats(t)}</div></div></article>`}).join('');if(!shown.length){grid.innerHTML=`<p class="empty-state">No tree matches “${searchEl.value}”${family!=='all'||classEl.value!=='all'?' in this view':''}. <button type="button" id="clear-search">Clear search</button></p>`;document.getElementById('clear-search').onclick=()=>{searchEl.value='';render()}}updateStatus(shown);paint();if(animate)animateFrom(first);syncUrl()}
function syncUrl(){const u=new URL(location.href);u.searchParams.set('sort',sort);u.searchParams.set('class',classEl.value);u.searchParams.set('family',family);u.searchParams.set('color',palette);if(crossYear)u.searchParams.set('year',crossYear);else u.searchParams.delete('year');if(searchEl.value)u.searchParams.set('q',searchEl.value);else u.searchParams.delete('q');history.replaceState(null,'',u)}
function syncPalette(){paletteEl.querySelectorAll('[data-palette]').forEach(b=>{const active=b.dataset.palette===palette;b.classList.toggle('active',active);b.setAttribute('aria-pressed',String(active))});const legend=document.getElementById('legend');legend.dataset.palette=palette;legend.setAttribute('aria-label',`${palette==='wood'?'Wood':'Market'} colors progress from large loss through near zero to large gain`)}
function syncFamily(){familiesEl.querySelectorAll('[data-family]').forEach(b=>b.classList.toggle('active',b.dataset.family===family))}
// Carry the full collection context to the specimen so its prev/next matches this
// view AND its "back" restores exactly what you left.
function openSpecimen(id){const q=new URLSearchParams({from:'arboretum',sort,class:classEl.value,family,color:palette});if(crossYear)q.set('year',crossYear);if(searchEl.value)q.set('q',searchEl.value);if(window.PRETTY_ROUTES)location.href=`specimen/${id}/?${q}`;else{q.set('id',id);location.href=`specimen/?${q}`}}
familiesEl.onclick=e=>{const b=e.target.closest('[data-family]');if(!b)return;family=b.dataset.family;syncFamily();render()};
sortEl.onchange=()=>{sort=sortEl.value;render()};
paletteEl.onclick=e=>{const b=e.target.closest('[data-palette]');if(!b||b.dataset.palette===palette)return;palette=b.dataset.palette;syncPalette();syncUrl();paint()};
classEl.onchange=()=>render();searchEl.oninput=()=>render();crossEl.onchange=()=>{crossYear=crossEl.value?+crossEl.value:null;render(false)};window.addEventListener('resize',paint);
grid.onclick=e=>{const card=e.target.closest('.specimen');if(card)openSpecimen(card.dataset.id)};grid.onkeydown=e=>{const card=e.target.closest('.specimen');if(card&&(e.key==='Enter'||e.key===' ')){e.preventDefault();openSpecimen(card.dataset.id)}};
grid.onmousemove=e=>{const cv=e.target.closest('canvas');if(!cv)return;const r=cv.getBoundingClientRect(),b=LivingTrees.detailedRingAt(cv._geo,cv._size/2,cv._size/2,e.clientX-r.left,e.clientY-r.top);if(!b){tip.style.opacity=0;if(cv._hoverYear){cv._hoverYear=null;paintOne(cv)}return}if(cv._hoverYear!==b.year){cv._hoverYear=b.year;paintOne(cv)}const t=trees.find(x=>x.id===cv.dataset.id),ring=t.rings.find(x=>x.year===b.year);tip.innerHTML=`<b>${t.id.toUpperCase()} · ${b.year}${ring.partial?' (partial)':''}</b><br>return ${ring.ret>=0?'+':''}${(ring.ret*100).toFixed(1)}% · volatility ${(ring.vol*100).toFixed(1)}%<br>max drawdown ${(ring.max_dd*100).toFixed(1)}% · trough ${ring.scar_date||'—'}`;tip.style.left=Math.min(innerWidth-270,e.clientX+14)+'px';tip.style.top=Math.max(8,e.clientY+14)+'px';tip.style.opacity=1};grid.onmouseleave=()=>{tip.style.opacity=0;document.querySelectorAll('.specimen canvas').forEach(cv=>{if(cv._hoverYear){cv._hoverYear=null;paintOne(cv)}})};
LivingTrees.load('data/rings.json').then(d=>{trees=d.trees.filter(t=>t.featured).map((t,i)=>Object.assign(t,{_i:i}));insights=TreeInsights.create(trees);const years=[...new Set(trees.flatMap(t=>t.rings.map(r=>r.year)))].sort((a,b)=>b-a),events={2002:'dot-com trough',2009:'GFC trough',2018:'crypto winter',2020:'COVID shock',2022:'rates shock',2026:'current year'};// Climate years — computed in the bake: share of living trees scarred that year × how tightly the troughs cluster in the calendar.
const climate=(d.climate_years||[]).slice().sort((a,b)=>b.year-a.year);crossEl.innerHTML+=(climate.length?`<optgroup label="Climate years — the forest wounded together">${climate.map(c=>`<option value="${c.year}">${c.year} · ${Math.round(c.breadth*100)}% of ${c.n} trees scarred${events[c.year]?` · ${events[c.year]}`:''}</option>`).join('')}</optgroup>`:'')+`<optgroup label="Every year">${years.map(y=>`<option value="${y}">${y}${events[y]?` · ${events[y]}`:''}</option>`).join('')}</optgroup>`;const p=new URLSearchParams(location.search);if(Collection.SORTS[p.get('sort')])sort=p.get('sort');if([...classEl.options].some(o=>o.value===p.get('class')))classEl.value=p.get('class');if(TreeInsights.FAMILY_LABELS[p.get('family')]||p.get('family')==='all')family=p.get('family');if(['wood','market'].includes(p.get('color')))palette=p.get('color');if(p.get('q'))searchEl.value=p.get('q');if(years.includes(+p.get('year'))){crossYear=+p.get('year');crossEl.value=String(crossYear)}sortEl.value=sort;syncFamily();syncPalette();document.getElementById('freshness').textContent=`Prices through ${new Date(`${d.data_through}T12:00:00Z`).toLocaleDateString(undefined,{year:'numeric',month:'short',day:'numeric',timeZone:'UTC'})} · coverage varies by asset`;render(false)}).catch(error=>{console.error(error);document.querySelector('.toolbar').hidden=true;grid.hidden=true;document.getElementById('load-error').hidden=false;document.getElementById('freshness').textContent='Data coverage unavailable';});
