const grid=document.getElementById('grid'),classEl=document.getElementById('class'),colsEl=document.getElementById('cols'),searchEl=document.getElementById('search'),crossEl=document.getElementById('cross'),tip=document.getElementById('tip');
let trees=[],lens='curated',crossYear=null,raf=0;
function metric(t){return LivingTrees.metrics(t,9999)}
function openScars(t){return (t.scars||[]).filter(s=>s.r_year==null)}
const LENSES={
  curated:{title:'Explore fifty financial specimens',compare:(a,b)=>a._i-b._i,value:()=>''},
  growth:{title:'Fast growers ranked by annualized return',compare:(a,b)=>b.cagr-a.cagr,value:t=>`${(t.cagr*100).toFixed(1)}% CAGR`},
  quiet:{title:'Quiet compounders pair gains with low volatility',filter:t=>t.cagr>0,compare:(a,b)=>a.mean_vol-b.mean_vol,value:t=>`${(t.mean_vol*100).toFixed(1)}% mean vol`},
  age:{title:'Old growth carries the longest visible record',compare:(a,b)=>b.n_rings-a.n_rings,value:t=>`${t.n_rings} rings`},
  drawdown:{title:'Deep scars rank the worst historical wounds',compare:(a,b)=>a.worst_dd-b.worst_dd,value:t=>`${(t.worst_dd*100).toFixed(1)}% worst DD`},
  positive:{title:'Consistent trees rank by positive-year share',compare:(a,b)=>metric(b).positive-metric(a).positive,value:t=>`${Math.round(metric(t).positive*100)}% positive years`},
  wounded:{title:'Still-wounded trees have unrecovered drawdowns',filter:t=>openScars(t).length,compare:(a,b)=>Math.min(...openScars(a).map(s=>s.depth))-Math.min(...openScars(b).map(s=>s.depth)),value:t=>`${(Math.min(...openScars(t).map(s=>s.depth))*100).toFixed(1)}% open wound`}
};
function list(){const q=searchEl.value.trim().toLowerCase(),cfg=LENSES[lens];return trees.filter(t=>(classEl.value==='all'||t.cls===classEl.value)&&(!q||t.id.includes(q))&&(!cfg.filter||cfg.filter(t))).sort(cfg.compare)}
function focusedRing(t){return crossYear?t.rings.find(r=>r.year===crossYear):null}
function cardStats(t){const r=focusedRing(t);if(r)return `<b>${r.ret>=0?'+':''}${(r.ret*100).toFixed(1)}%</b> in ${crossYear}<br><b>${(r.vol*100).toFixed(1)}%</b> volatility`;const m=metric(t),lensValue=LENSES[lens].value(t);return lensValue?`<b>${lensValue}</b><br>${(m.worst*100).toFixed(1)}% worst DD`:`<b>${(m.cagr*100).toFixed(1)}%</b> CAGR<br><b>${(m.worst*100).toFixed(1)}%</b> worst DD`}
function paintOne(cv){const t=trees.find(x=>x.id===cv.dataset.id),s=cv.clientWidth,dpr=Math.min(devicePixelRatio||1,1.6);cv.style.height=s+'px';cv.width=Math.round(s*dpr);cv.height=Math.round(s*dpr);const g=cv.getContext('2d');g.setTransform(dpr,0,0,dpr,0,0);g.clearRect(0,0,s,s);cv._size=s;cv._geo=LivingTrees.drawDetailedRings(g,t,s/2,s/2,s*.42,9999,{years:+colsEl.value===2,focusYear:crossYear,highlightYear:cv._hoverYear})}
function paint(){cancelAnimationFrame(raf);raf=requestAnimationFrame(()=>document.querySelectorAll('.specimen canvas').forEach(paintOne))}
function animateFrom(first){requestAnimationFrame(()=>document.querySelectorAll('.specimen').forEach(card=>{const old=first.get(card.dataset.id);if(!old)return;const now=card.getBoundingClientRect(),dx=old.left-now.left,dy=old.top-now.top;if(Math.abs(dx)>1||Math.abs(dy)>1)card.animate([{transform:`translate(${dx}px,${dy}px)`},{transform:'translate(0,0)'}],{duration:520,easing:'cubic-bezier(.2,.75,.25,1)'})}))}
function updateStatus(shown){if(crossYear){const rings=shown.map(focusedRing).filter(Boolean),negative=rings.filter(r=>r.ret<0).length,scarred=shown.filter(t=>(t.scars||[]).some(s=>s.year===crossYear)).length;document.getElementById('headline').textContent=`${crossYear} scarred ${scarred} of ${rings.length} visible trees`;document.getElementById('status').textContent=`${negative} negative years · ${scarred} qualifying scars`}else{document.getElementById('headline').textContent=LENSES[lens].title;document.getElementById('status').textContent=`${shown.length} visible specimens`}}
function render(animate=true){const first=new Map([...document.querySelectorAll('.specimen')].map(el=>[el.dataset.id,el.getBoundingClientRect()]));grid.style.setProperty('--cols',colsEl.value);const shown=list(),ranked=lens!=='curated';grid.innerHTML=shown.map((t,i)=>{const m=metric(t);return `<article class="specimen" data-id="${t.id}" tabindex="0" role="link" aria-label="Open ${t.id.toUpperCase()} full specimen">${ranked?`<span class="rank">#${i+1}</span>`:''}<canvas data-id="${t.id}" aria-label="${t.id} annual rings"></canvas><div class="caption"><div><div class="ticker" style="color:${LivingTrees.CLASS_COLORS[t.cls]}">${t.id.toUpperCase()}</div><div class="class">${LivingTrees.CLASS_NAMES[t.cls]} · ${m.years} rings</div></div><div class="stats">${cardStats(t)}</div></div></article>`}).join('');updateStatus(shown);paint();if(animate)animateFrom(first);syncUrl()}
function syncUrl(){const u=new URL(location.href);u.searchParams.set('lens',lens);u.searchParams.set('class',classEl.value);u.searchParams.set('cols',colsEl.value);if(crossYear)u.searchParams.set('year',crossYear);else u.searchParams.delete('year');if(searchEl.value)u.searchParams.set('q',searchEl.value);else u.searchParams.delete('q');history.replaceState(null,'',u)}
function openSpecimen(id){location.href=`specimen/?id=${encodeURIComponent(id)}&from=arboretum`}
document.getElementById('lenses').onclick=e=>{const b=e.target.closest('[data-lens]');if(!b)return;lens=b.dataset.lens;document.querySelectorAll('[data-lens]').forEach(x=>x.classList.toggle('active',x===b));render()};classEl.onchange=()=>render();colsEl.onchange=()=>render(false);searchEl.oninput=()=>render();crossEl.onchange=()=>{crossYear=crossEl.value?+crossEl.value:null;render(false)};window.addEventListener('resize',paint);
grid.onclick=e=>{const card=e.target.closest('.specimen');if(card)openSpecimen(card.dataset.id)};grid.onkeydown=e=>{const card=e.target.closest('.specimen');if(card&&(e.key==='Enter'||e.key===' ')){e.preventDefault();openSpecimen(card.dataset.id)}};
grid.onmousemove=e=>{const cv=e.target.closest('canvas');if(!cv)return;const r=cv.getBoundingClientRect(),b=LivingTrees.detailedRingAt(cv._geo,cv._size/2,cv._size/2,e.clientX-r.left,e.clientY-r.top);if(!b){tip.style.opacity=0;if(cv._hoverYear){cv._hoverYear=null;paintOne(cv)}return}if(cv._hoverYear!==b.year){cv._hoverYear=b.year;paintOne(cv)}const t=trees.find(x=>x.id===cv.dataset.id),ring=t.rings.find(x=>x.year===b.year);tip.innerHTML=`<b>${t.id.toUpperCase()} · ${b.year}${ring.partial?' (partial)':''}</b><br>return ${ring.ret>=0?'+':''}${(ring.ret*100).toFixed(1)}% · volatility ${(ring.vol*100).toFixed(1)}%<br>max drawdown ${(ring.max_dd*100).toFixed(1)}% · trough ${ring.scar_date||'—'}`;tip.style.left=Math.min(innerWidth-270,e.clientX+14)+'px';tip.style.top=Math.max(8,e.clientY+14)+'px';tip.style.opacity=1};grid.onmouseleave=()=>{tip.style.opacity=0;document.querySelectorAll('.specimen canvas').forEach(cv=>{if(cv._hoverYear){cv._hoverYear=null;paintOne(cv)}})};
LivingTrees.load('data/rings.json').then(d=>{trees=d.trees.filter(t=>t.featured).map((t,i)=>Object.assign(t,{_i:i}));const years=[...new Set(trees.flatMap(t=>t.rings.map(r=>r.year)))].sort((a,b)=>b-a),events={2018:'crypto winter',2020:'COVID shock',2022:'rates shock',2026:'current year'};crossEl.innerHTML+=years.map(y=>`<option value="${y}">${y}${events[y]?` · ${events[y]}`:''}</option>`).join('');const p=new URLSearchParams(location.search);if(LENSES[p.get('lens')])lens=p.get('lens');if([...classEl.options].some(o=>o.value===p.get('class')))classEl.value=p.get('class');if(['2','3','4'].includes(p.get('cols')))colsEl.value=p.get('cols');if(p.get('q'))searchEl.value=p.get('q');if(years.includes(+p.get('year'))){crossYear=+p.get('year');crossEl.value=String(crossYear)}document.querySelectorAll('[data-lens]').forEach(x=>x.classList.toggle('active',x.dataset.lens===lens));render(false)}).catch(console.error);
