const cv=document.getElementById('canvas'),art=document.getElementById('art'),tickerEl=document.getElementById('ticker'),tip=document.getElementById('tip');let data,trees=[],tree,insights,raf=0,hoverYear=null,geo=null,canvasSize=0;
const params=new URLSearchParams(location.search),origin=params.get('from')==='wall'?'../labs/experiments/specimen-wall/':'../';document.getElementById('back').href=origin;
function pct(x){return (x*100).toFixed(1)+'%'}function signed(x){return (x>=0?'+':'')+pct(x)}
function setUrl(){const u=new URL(location.href);u.searchParams.set('id',tree.id);u.searchParams.set('from',params.get('from')||'arboretum');history.replaceState(null,'',u)}
function paint(){cancelAnimationFrame(raf);raf=requestAnimationFrame(()=>{const available=Math.min(art.clientWidth,art.clientHeight||art.clientWidth),s=Math.max(240,Math.floor(available)),dpr=Math.min(devicePixelRatio||1,2);canvasSize=s;cv.style.width=s+'px';cv.style.height=s+'px';cv.width=Math.round(s*dpr);cv.height=Math.round(s*dpr);const g=cv.getContext('2d');g.setTransform(dpr,0,0,dpr,0,0);g.clearRect(0,0,s,s);geo=LivingTrees.drawDetailedRings(g,tree,s/2,s/2,s*.445,9999,{years:true,fibers:true,highlightYear:hoverYear})})}
function update(){const m=LivingTrees.metrics(tree,9999);if(!m)return;const family=TreeInsights.familyOf(insights,tree),from=encodeURIComponent(params.get('from')||'arboretum');document.title=tree.id.toUpperCase()+' Full Specimen — Money Trees';document.getElementById('title').textContent=`${tree.id.toUpperCase()} carries ${m.years} visible annual rings`;document.getElementById('name').textContent=tree.id.toUpperCase();document.getElementById('classline').textContent=`${LivingTrees.CLASS_NAMES[tree.cls]} · ${TreeInsights.FAMILY_LABELS[family]} · ${tree.first_year}–${tree.last_year}`;document.getElementById('classline').style.color=LivingTrees.CLASS_COLORS[tree.cls];document.getElementById('facts').innerHTML=`<span>visible rings</span><b>${m.years}</b><span>annualized growth</span><b>${signed(m.cagr)}</b><span>positive years</span><b>${Math.round(m.positive*100)}%</b><span>mean volatility</span><b>${pct(m.meanVol)}</b><span>worst drawdown</span><b>${pct(m.worst)}</b><span>accumulated growth</span><b>${signed(Math.exp(m.sumLg)-1)}</b>`;document.getElementById('field-notes').innerHTML=TreeInsights.notes(tree).map(note=>`<p class="field-note">${note}</p>`).join('');document.getElementById('kin').innerHTML=TreeInsights.relatives(insights,tree).map(({tree:t})=>{const f=TreeInsights.familyOf(insights,t);return`<a class="kin-link" href="?id=${encodeURIComponent(t.id)}&from=${from}"><b style="color:${LivingTrees.CLASS_COLORS[t.cls]}">${t.id.toUpperCase()}</b><span>${TreeInsights.FAMILY_LABELS[f]}</span></a>`}).join('');document.getElementById('scars').innerHTML=m.scars.length?m.scars.slice().reverse().map(s=>`<div class="scar"><b>${s.date||s.year}</b> · ${pct(s.depth)} drawdown<br>${s.r_year?`recovered ${s.r_date||s.r_year}`:'still unrecovered in visible data'}</div>`).join(''):'<p class="empty">No qualifying major scars yet.</p>';tickerEl.value=tree.id;setUrl();hoverYear=null;paint()}
function select(id){tree=trees.find(t=>t.id===id)||trees[0];update()}
function move(dir){const i=trees.indexOf(tree);select(trees[(i+dir+trees.length)%trees.length].id)}
document.getElementById('prev').onclick=()=>move(-1);document.getElementById('next').onclick=()=>move(1);tickerEl.onchange=e=>select(e.target.value);window.addEventListener('resize',paint);window.addEventListener('keydown',e=>{if(e.key==='ArrowLeft')move(-1);if(e.key==='ArrowRight')move(1);if(e.key==='Escape')location.href=origin});
cv.onmousemove=e=>{const r=cv.getBoundingClientRect(),b=LivingTrees.detailedRingAt(geo,canvasSize/2,canvasSize/2,e.clientX-r.left,e.clientY-r.top);if(!b){tip.style.opacity=0;if(hoverYear){hoverYear=null;paint()}return}if(hoverYear!==b.year){hoverYear=b.year;paint()}const ring=tree.rings.find(x=>x.year===b.year);tip.innerHTML=`<b>${tree.id.toUpperCase()} · ${b.year}${ring.partial?' (partial)':''}</b><br>return ${ring.ret>=0?'+':''}${pct(ring.ret)} · volatility ${pct(ring.vol)}<br>max drawdown ${pct(ring.max_dd)} · trough ${ring.scar_date||'—'}`;tip.style.left=Math.min(innerWidth-280,e.clientX+15)+'px';tip.style.top=Math.max(8,e.clientY+15)+'px';tip.style.opacity=1};cv.onmouseleave=()=>{tip.style.opacity=0;hoverYear=null;paint()};
LivingTrees.load('../data/rings.json').then(d=>{data=d;trees=d.trees.filter(t=>t.featured);insights=TreeInsights.create(trees);tickerEl.innerHTML=trees.map(t=>`<option value="${t.id}">${t.id.toUpperCase()} · ${LivingTrees.CLASS_NAMES[t.cls]}</option>`).join('');select((params.get('id')||'btc').toLowerCase())}).catch(console.error);
