const cv=document.getElementById('canvas'),art=document.getElementById('art'),tickerEl=document.getElementById('ticker'),paletteEl=document.getElementById('palette'),labelsEl=document.getElementById('year-labels'),tip=document.getElementById('tip');
let data,trees=[],tree,insights,seq=[],raf=0,hoverYear=null,geo=null,canvasSize=0;
const params=new URLSearchParams(location.search),origin=params.get('from')==='wall'?'../labs/experiments/specimen-wall/':'../';
let palette=['wood','market'].includes(params.get('color'))?params.get('color'):'wood';
let yearLabels=params.get('labels')!=='hide';
// The collection context we arrived with — drives prev/next order AND the back link.
const ctx={sort:params.get('sort')||'curated',cls:params.get('class')||'all',family:params.get('family')||'all',q:params.get('q')||'',year:params.get('year')||''};
function pct(x){return (x*100).toFixed(1)+'%'}function signed(x){return (x>=0?'+':'')+pct(x)}
function grow(m){const mult=Math.exp(m.sumLg);return mult>=10?`${mult>=1000?Math.round(mult).toLocaleString():mult.toFixed(1)}×`:signed(mult-1)}
function rgb(c){return `rgb(${c[0]},${c[1]},${c[2]})`}
function posterText(g,text,x,y,size,color='#eee9dd',font='ui-sans-serif,system-ui,sans-serif',weight=400,align='left'){g.fillStyle=color;g.font=`${weight} ${size}px ${font}`;g.textAlign=align;g.fillText(text,x,y)}
function drawPoster(){const W=2400,H=3000,out=document.createElement('canvas');out.width=W;out.height=H;const g=out.getContext('2d'),m=LivingTrees.metrics(tree),family=TreeInsights.familyOf(insights,tree),p=LivingTrees.PALETTES[palette];
  const bg=g.createLinearGradient(0,0,0,H);bg.addColorStop(0,'#101a14');bg.addColorStop(.58,'#07100d');bg.addColorStop(1,'#13120c');g.fillStyle=bg;g.fillRect(0,0,W,H);
  const glow=g.createRadialGradient(W*.5,1080,80,W*.5,1080,1080);glow.addColorStop(0,'rgba(92,104,68,.22)');glow.addColorStop(1,'rgba(7,16,13,0)');g.fillStyle=glow;g.fillRect(0,300,W,1900);
  posterText(g,'MONEY TREES',150,145,28,'#d8b66f','ui-monospace,Menlo,monospace',600);posterText(g,`${tree.id.toUpperCase()} · ${tree.first_year}–${tree.last_year}`,150,260,86,'#f0e9da','Georgia,serif',500);posterText(g,`${LivingTrees.CLASS_NAMES[tree.cls]} · ${TreeInsights.FAMILY_LABELS[family]} · ${m.years} annual rings`,150,330,30,'#a9a294','ui-sans-serif,system-ui,sans-serif',400);
  LivingTrees.drawDetailedRings(g,tree,W/2,1290,860,9999,{palette,years:yearLabels,fibers:true});
  g.fillStyle='rgba(20,27,22,.92)';g.fillRect(150,2225,2100,225);g.strokeStyle='rgba(228,218,190,.18)';g.lineWidth=2;g.strokeRect(150,2225,2100,225);
  const stats=[['ACCUMULATED GROWTH',grow(m)],['ANNUALIZED GROWTH',signed(m.cagr)],['MEAN VOLATILITY',pct(m.meanVol)],['WORST DRAWDOWN',pct(m.worst)]];stats.forEach((s,i)=>{const x=205+i*520;posterText(g,s[0],x,2295,21,'#8f897d','ui-monospace,Menlo,monospace',500);posterText(g,s[1],x,2390,54,i===0?'#e6b85c':'#eee9dd','Georgia,serif',600)});
  posterText(g,`${palette==='wood'?'NATURAL WOOD':'MARKET'} RETURN COLOR`,150,2545,20,'#8f897d','ui-monospace,Menlo,monospace',600);const cols=[p.neg,p.negNear,p.mid,p.posNear,p.pos],colorLabels=['BIG LOSS','MILD LOSS','~0','MILD GAIN','BIG GAIN'];cols.forEach((c,i)=>{const x=150+i*150;g.fillStyle=rgb(c);g.fillRect(x,2580,146,34);posterText(g,colorLabels[i],x+73,2655,14,'#9f998b','ui-monospace,Menlo,monospace',500,'center')});
  const key=[['RING WIDTH','Wider = stronger annual growth'],['DARKNESS + GRAIN','More = higher realized volatility'],['SCAR','Major drawdown; open to bark = unrecovered'],['ONE BAND','One calendar year']];key.forEach((s,i)=>{const col=i%2,row=Math.floor(i/2),x=1200+col*585,y=2550+row*150;posterText(g,s[0],x,y,20,'#d8c9a9','ui-monospace,Menlo,monospace',600);posterText(g,s[1],x,y+42,22,'#9f998b','ui-sans-serif,system-ui,sans-serif',400)});
  posterText(g,`${m.scars.length} qualifying scar${m.scars.length===1?'':'s'} · ${Math.round(m.positive*100)}% positive years`,150,2870,24,'#b8b09f','ui-sans-serif,system-ui,sans-serif',400);posterText(g,'Financial history rendered as annual tree rings',2250,2870,22,'#777f76','ui-sans-serif,system-ui,sans-serif',400,'right');posterText(g,'money trees · financial dendrochronology',1200,2940,20,'#776f61','ui-monospace,Menlo,monospace',500,'center');return out}
async function downloadPoster(){const b=document.getElementById('download-poster'),old=b.textContent;b.disabled=true;b.textContent='Rendering…';try{const out=drawPoster(),blob=await new Promise(resolve=>out.toBlob(resolve,'image/png'));if(!blob)throw new Error('PNG export failed');const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`money-tree-${tree.id}-${palette}.png`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}catch(e){console.error(e);b.textContent='Export failed';setTimeout(()=>b.textContent=old,1600)}finally{b.disabled=false;if(b.textContent==='Rendering…')b.textContent=old}}
// Rebuild the arboretum query so "back" restores exactly the view you left.
function arbParams(){const u=new URLSearchParams({sort:ctx.sort,class:ctx.cls,family:ctx.family,color:palette});if(ctx.q)u.set('q',ctx.q);if(ctx.year)u.set('year',ctx.year);return u}
function backHref(){return origin==='../'?`../?${arbParams()}`:origin}
function navList(){return seq.length&&seq.some(t=>t.id===tree.id)?seq:trees}
function setUrl(){const u=new URL(location.href);u.searchParams.set('id',tree.id);u.searchParams.set('from',params.get('from')||'arboretum');u.searchParams.set('color',palette);u.searchParams.set('labels',yearLabels?'show':'hide');history.replaceState(null,'',u)}
function syncPalette(){paletteEl.querySelectorAll('[data-palette]').forEach(b=>{const active=b.dataset.palette===palette;b.classList.toggle('active',active);b.setAttribute('aria-pressed',String(active))});const legend=document.getElementById('legend');legend.dataset.palette=palette;legend.setAttribute('aria-label',`${palette==='wood'?'Wood':'Market'} colors progress from large loss through near zero to large gain`);document.querySelectorAll('.kin-link').forEach(a=>{const u=new URL(a.href);u.searchParams.set('color',palette);a.href=u});document.getElementById('back').href=backHref()}
function syncYearLabels(){labelsEl.querySelectorAll('[data-labels]').forEach(b=>{const active=(b.dataset.labels==='show')===yearLabels;b.classList.toggle('active',active);b.setAttribute('aria-pressed',String(active))});document.querySelectorAll('.kin-link').forEach(a=>{const u=new URL(a.href);u.searchParams.set('labels',yearLabels?'show':'hide');a.href=u})}
function paint(){if(!tree)return;cancelAnimationFrame(raf);raf=requestAnimationFrame(()=>{if(!tree)return;const available=Math.min(art.clientWidth,art.clientHeight||art.clientWidth),s=Math.max(240,Math.floor(available)),dpr=Math.min(devicePixelRatio||1,2);canvasSize=s;cv.style.width=s+'px';cv.style.height=s+'px';cv.width=Math.round(s*dpr);cv.height=Math.round(s*dpr);const g=cv.getContext('2d');g.setTransform(dpr,0,0,dpr,0,0);g.clearRect(0,0,s,s);geo=LivingTrees.drawDetailedRings(g,tree,s/2,s/2,s*.445,9999,{palette,years:yearLabels,fibers:true,highlightYear:hoverYear})})}
function update(){const m=LivingTrees.metrics(tree,9999);if(!m)return;const family=TreeInsights.familyOf(insights,tree),from=encodeURIComponent(params.get('from')||'arboretum'),kinParams=arbParams();
  document.title=tree.id.toUpperCase()+' Full Specimen — Money Trees';
  document.getElementById('title').textContent=`${tree.id.toUpperCase()} carries ${m.years} visible annual rings`;
  document.getElementById('crumb-context').textContent=ctx.family!=='all'?` · ${TreeInsights.FAMILY_LABELS[ctx.family]}`:(ctx.cls!=='all'?` · ${LivingTrees.CLASS_NAMES[ctx.cls]}`:'');
  document.getElementById('name').textContent=tree.id.toUpperCase();
  const classline=document.getElementById('classline');classline.textContent=`${LivingTrees.CLASS_NAMES[tree.cls]} · ${TreeInsights.FAMILY_LABELS[family]} · ${tree.first_year}–${tree.last_year}`;classline.style.color=LivingTrees.CLASS_COLORS[tree.cls];
  document.getElementById('hero').innerHTML=`<span class="hero-num">${grow(m)}</span><span class="hero-label">accumulated growth over ${m.years} years</span>`;
  document.getElementById('facts').innerHTML=`<span>annualized growth</span><b>${signed(m.cagr)}</b><span>positive years</span><b>${Math.round(m.positive*100)}%</b><span>mean volatility</span><b>${pct(m.meanVol)}</b><span>worst drawdown</span><b>${pct(m.worst)}</b>`;
  document.getElementById('field-notes').innerHTML=TreeInsights.notes(tree).map(note=>`<p class="field-note">${note}</p>`).join('');
  document.getElementById('kin').innerHTML=TreeInsights.relatives(insights,tree).map(({tree:t})=>{const f=TreeInsights.familyOf(insights,t),u=new URLSearchParams(kinParams);u.set('id',t.id);u.set('from',from);u.set('labels',yearLabels?'show':'hide');return`<a class="kin-link" href="?${u}"><b style="color:${LivingTrees.CLASS_COLORS[t.cls]}">${t.id.toUpperCase()}</b><span>${TreeInsights.FAMILY_LABELS[f]}</span></a>`}).join('');
  document.getElementById('scar-count').textContent=m.scars.length?m.scars.length:'';
  document.getElementById('scars').innerHTML=m.scars.length?m.scars.slice().reverse().map(s=>`<div class="scar"><b>${s.date||s.year}</b> · ${pct(s.depth)} drawdown<br>${s.r_year?`recovered ${s.r_date||s.r_year}`:'still unrecovered in visible data'}</div>`).join(''):'<p class="empty">No qualifying major scars yet.</p>';
  tickerEl.value=tree.id;setUrl();document.getElementById('back').href=backHref();hoverYear=null;paint()}
function select(id){tree=trees.find(t=>t.id===id)||trees[0];update()}
function move(dir){const nav=navList(),i=nav.indexOf(tree);select(nav[(i+dir+nav.length)%nav.length].id)}
document.getElementById('prev').onclick=()=>move(-1);document.getElementById('next').onclick=()=>move(1);tickerEl.onchange=e=>select(e.target.value);paletteEl.onclick=e=>{const b=e.target.closest('[data-palette]');if(!b||b.dataset.palette===palette)return;palette=b.dataset.palette;syncPalette();setUrl();paint()};labelsEl.onclick=e=>{const b=e.target.closest('[data-labels]');if(!b)return;const next=b.dataset.labels==='show';if(next===yearLabels)return;yearLabels=next;syncYearLabels();setUrl();paint()};document.getElementById('download-poster').onclick=downloadPoster;window.addEventListener('resize',paint);window.addEventListener('keydown',e=>{if(e.target.tagName==='SELECT')return;if(e.key==='ArrowLeft')move(-1);if(e.key==='ArrowRight')move(1);if(e.key==='Escape')location.href=backHref()});
cv.onmousemove=e=>{const r=cv.getBoundingClientRect(),b=LivingTrees.detailedRingAt(geo,canvasSize/2,canvasSize/2,e.clientX-r.left,e.clientY-r.top);if(!b){tip.style.opacity=0;if(hoverYear){hoverYear=null;paint()}return}if(hoverYear!==b.year){hoverYear=b.year;paint()}const ring=tree.rings.find(x=>x.year===b.year);tip.innerHTML=`<b>${tree.id.toUpperCase()} · ${b.year}${ring.partial?' (partial)':''}</b><br>return ${ring.ret>=0?'+':''}${pct(ring.ret)} · volatility ${pct(ring.vol)}<br>max drawdown ${pct(ring.max_dd)} · trough ${ring.scar_date||'—'}`;tip.style.left=Math.min(innerWidth-280,e.clientX+15)+'px';tip.style.top=Math.max(8,e.clientY+15)+'px';tip.style.opacity=1};cv.onmouseleave=()=>{tip.style.opacity=0;hoverYear=null;paint()};
LivingTrees.load('../data/rings.json').then(d=>{data=d;trees=d.trees.filter(t=>t.featured).map((t,i)=>Object.assign(t,{_i:i}));insights=TreeInsights.create(trees);seq=Collection.order(trees,insights,{sort:ctx.sort,cls:ctx.cls,family:ctx.family,q:ctx.q});tickerEl.innerHTML=trees.map(t=>`<option value="${t.id}">${t.id.toUpperCase()} · ${LivingTrees.CLASS_NAMES[t.cls]}</option>`).join('');document.getElementById('back').href=backHref();syncPalette();syncYearLabels();select((params.get('id')||'btc').toLowerCase())}).catch(console.error);
