const cv=document.getElementById('canvas'),art=document.getElementById('art'),tickerEl=document.getElementById('ticker'),paletteEl=document.getElementById('palette'),labelsEl=document.getElementById('year-labels'),tip=document.getElementById('tip'),ringReadout=document.getElementById('ring-readout');
let data,trees=[],tree,insights,seq=[],raf=0,hoverYear=null,selectedYear=null,geo=null,canvasSize=0;
const params=new URLSearchParams(location.search),origin=params.get('from')==='wall'?'../labs/experiments/specimen-wall/':'../';
let palette=['wood','market'].includes(params.get('color'))?params.get('color'):'wood';
let yearLabels=params.get('labels')==='show';
document.getElementById('retry-load').onclick=()=>location.reload();
// The collection context we arrived with — drives prev/next order AND the back link.
const ctx={sort:params.get('sort')||'curated',cls:params.get('class')||'all',family:params.get('family')||'all',q:params.get('q')||'',year:params.get('year')||''};
const BASIS_COPY={total:'Total-return index: dividends reinvested.',adjusted:'Dividend- and split-adjusted closes; the vendor’s dividend adjustment is thinner before 2013, so early growth reads a little low.',spot:'Spot price; no yield.'};
function pct(x){return (x*100).toFixed(1)+'%'}function signed(x){return (x>=0?'+':'')+pct(x)}
function sig2(x){const p=Math.pow(10,Math.floor(Math.log10(x))-1);return Math.round(x/p)*p}
// Accumulated growth = (1+CAGR)^years, shown to two significant figures. Rings are
// quantized to a whole percent, so compounding them would print false precision and
// disagree with the CAGR beneath it.
function grow(m){const mult=Math.pow(1+m.cagr,m.ageYears);if(mult<10)return signed(mult-1);const r=sig2(mult);return `~${r>=1000?Math.round(r).toLocaleString():r.toFixed(r<100?1:0)}×`}
function rgb(c){return `rgb(${c[0]},${c[1]},${c[2]})`}
function posterText(g,text,x,y,size,color='#eee9dd',font='ui-sans-serif,system-ui,sans-serif',weight=400,align='left'){g.fillStyle=color;g.font=`${weight} ${size}px ${font}`;g.textAlign=align;g.fillText(text,x,y)}
function drawPoster(){const W=2400,H=3000,out=document.createElement('canvas');out.width=W;out.height=H;const g=out.getContext('2d'),m=LivingTrees.metrics(tree),family=TreeInsights.familyOf(insights,tree),p=LivingTrees.PALETTES[palette];
  const bg=g.createLinearGradient(0,0,0,H);bg.addColorStop(0,'#101a14');bg.addColorStop(.58,'#07100d');bg.addColorStop(1,'#13120c');g.fillStyle=bg;g.fillRect(0,0,W,H);
  const glow=g.createRadialGradient(W*.5,1080,80,W*.5,1080,1080);glow.addColorStop(0,'rgba(92,104,68,.22)');glow.addColorStop(1,'rgba(7,16,13,0)');g.fillStyle=glow;g.fillRect(0,300,W,1900);
  posterText(g,'MONEY TREE FOREST',150,145,28,'#6fbf8a','ui-monospace,Menlo,monospace',600);posterText(g,`${tree.name} · ${tree.first_year}–${tree.last_year}`,150,260,86,'#f0e9da','Georgia,serif',500);posterText(g,`${tree.id.toUpperCase()} · ${LivingTrees.CLASS_NAMES[tree.cls]} · ${TreeInsights.FAMILY_LABELS[family]} · ${m.years} annual rings`,150,330,30,'#a9a294','ui-sans-serif,system-ui,sans-serif',400);
  LivingTrees.drawDetailedRings(g,tree,W/2,1290,860,9999,{palette,years:yearLabels,fibers:true});
  g.fillStyle='rgba(20,27,22,.92)';g.fillRect(150,2225,2100,225);g.strokeStyle='rgba(228,218,190,.18)';g.lineWidth=2;g.strokeRect(150,2225,2100,225);
  const stats=[['ACCUMULATED GROWTH',grow(m)],['ANNUALIZED GROWTH',signed(m.cagr)],['MEAN VOLATILITY',pct(m.meanVol)],['WORST DRAWDOWN',pct(m.worst)]];stats.forEach((s,i)=>{const x=205+i*520;posterText(g,s[0],x,2295,21,'#8f897d','ui-monospace,Menlo,monospace',500);posterText(g,s[1],x,2390,54,i===0?'#6fbf8a':'#eee9dd','Georgia,serif',600)});
  posterText(g,`${palette==='wood'?'NATURAL WOOD':'MARKET'} RETURN COLOR`,150,2545,20,'#8f897d','ui-monospace,Menlo,monospace',600);const cols=[p.neg,p.negNear,p.mid,p.posNear,p.pos],colorLabels=['BIG LOSS','MILD LOSS','~0','MILD GAIN','BIG GAIN'];cols.forEach((c,i)=>{const x=150+i*150;g.fillStyle=rgb(c);g.fillRect(x,2580,146,34);posterText(g,colorLabels[i],x+73,2655,14,'#9f998b','ui-monospace,Menlo,monospace',500,'center')});
  const key=[['RING WIDTH','Wider = stronger annual growth'],['DARKNESS + GRAIN','More = higher realized volatility'],['SCAR','Major drawdown; open to bark = unrecovered'],['ONE BAND','One calendar year']];key.forEach((s,i)=>{const col=i%2,row=Math.floor(i/2),x=1200+col*585,y=2550+row*150;posterText(g,s[0],x,y,20,'#d8c9a9','ui-monospace,Menlo,monospace',600);posterText(g,s[1],x,y+42,22,'#9f998b','ui-sans-serif,system-ui,sans-serif',400)});
  posterText(g,`${m.scars.length} qualifying scar${m.scars.length===1?'':'s'} · ${Math.round(m.positive*100)}% positive years`,150,2870,24,'#b8b09f','ui-sans-serif,system-ui,sans-serif',400);posterText(g,'Financial history rendered as annual tree rings',2250,2870,22,'#777f76','ui-sans-serif,system-ui,sans-serif',400,'right');posterText(g,'moneytreeforest.com',1200,2940,22,'#9fcfae','ui-monospace,Menlo,monospace',600,'center');return out}
async function downloadPoster(){const b=document.getElementById('download-poster'),old=b.textContent;b.disabled=true;b.textContent='Rendering…';try{const out=drawPoster(),blob=await new Promise(resolve=>out.toBlob(resolve,'image/png'));if(!blob)throw new Error('PNG export failed');const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`money-tree-${tree.id}-${palette}.png`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}catch(e){console.error(e);b.textContent='Export failed';setTimeout(()=>b.textContent=old,1600)}finally{b.disabled=false;if(b.textContent==='Rendering…')b.textContent=old}}
// Rebuild the forest query so "back" restores exactly the view you left.
function arbParams(){const u=new URLSearchParams({sort:ctx.sort,class:ctx.cls,family:ctx.family,color:palette});if(ctx.q)u.set('q',ctx.q);if(ctx.year)u.set('year',ctx.year);return u}
function backHref(){return origin==='../'?`../?${arbParams()}`:origin}
function navList(){return seq.length&&seq.some(t=>t.id===tree.id)?seq:trees}
// Production builds pre-render /tree/<id>/ (real link previews, sitemap) and set
// window.PRETTY_ROUTES; the app then writes and links that form. Without a build the
// page lives at /tree/?id=, which production keeps honouring for old links.
function treeHref(id,q){q.delete('id');return window.PRETTY_ROUTES?`/tree/${id}/?${q}`:(q.set('id',id),`?${q}`)}
function setUrl(){const q=new URLSearchParams(location.search);q.set('from',params.get('from')||'forest');q.set('color',palette);q.set('labels',yearLabels?'show':'hide');if(Immersive.isOpen())q.set('view','full');else q.delete('view');history.replaceState(null,'',treeHref(tree.id,q))}
function syncPalette(){paletteEl.querySelectorAll('[data-palette]').forEach(b=>{const active=b.dataset.palette===palette;b.classList.toggle('active',active);b.setAttribute('aria-pressed',String(active))});const legend=document.getElementById('legend');legend.dataset.palette=palette;legend.setAttribute('aria-label',`${palette==='wood'?'Wood':'Market'} colors progress from large loss through near zero to large gain`);document.querySelectorAll('.kin-link').forEach(a=>{const u=new URL(a.href);u.searchParams.set('color',palette);a.href=u});document.getElementById('back').href=backHref()}
function syncYearLabels(){labelsEl.querySelectorAll('[data-labels]').forEach(b=>{const active=(b.dataset.labels==='show')===yearLabels;b.classList.toggle('active',active);b.setAttribute('aria-pressed',String(active))});document.querySelectorAll('.kin-link').forEach(a=>{const u=new URL(a.href);u.searchParams.set('labels',yearLabels?'show':'hide');a.href=u})}
function activeYear(){return hoverYear||selectedYear}
function ringText(year){const ring=tree&&tree.rings.find(r=>r.year===year);if(!ring)return 'Tap or focus the tree, then use ← and → to inspect annual rings.';return `${tree.id.toUpperCase()} · ${ring.year}${ring.partial?' partial':''} · return ${ring.ret>=0?'+':''}${pct(ring.ret)} · volatility ${pct(ring.vol)} · max drawdown ${pct(ring.max_dd)}`}
function updateRingReadout(year){ringReadout.textContent=ringText(year);document.querySelectorAll('.year-table tr[data-year]').forEach(row=>row.classList.toggle('active',+row.dataset.year===year))}
function selectYear(year){if(!tree||!tree.rings.some(r=>r.year===year))return false;selectedYear=year;hoverYear=null;updateRingReadout(year);paint();if(Immersive.isOpen())Immersive.syncYear();return true}
function stepYear(dir){const years=tree.rings.map(r=>r.year),current=selectedYear||years[years.length-1],i=Math.max(0,years.indexOf(current)),next=years[Math.max(0,Math.min(years.length-1,i+dir))];selectYear(next)}
function paint(){if(!tree)return;cancelAnimationFrame(raf);raf=requestAnimationFrame(()=>{if(!tree)return;const available=Math.min(art.clientWidth,art.clientHeight||art.clientWidth),s=Math.max(240,Math.floor(available)),dpr=Math.min(devicePixelRatio||1,2);canvasSize=s;cv.style.width=s+'px';cv.style.height=s+'px';cv.width=Math.round(s*dpr);cv.height=Math.round(s*dpr);const g=cv.getContext('2d');g.setTransform(dpr,0,0,dpr,0,0);g.clearRect(0,0,s,s);const [vcx,vcy]=viewCenter(),R=s*.445*view.zoom;geo=LivingTrees.drawDetailedRings(g,tree,vcx,vcy,R,9999,{palette,years:yearLabels||view.zoom>1.6,fibers:true,highlightYear:activeYear(),labelPx:view.zoom>1?11:undefined,labelAngle:view.zoom>1?labelAngleV():undefined,strokeR:Math.min(R,s*.445*1.6),clip:{x0:0,y0:0,x1:s,y1:s}});cv.style.transform='';shownView={...view};syncZoomHud()})}
// In-place zoom on the detail canvas: same idea as the full view — the wood is
// re-rendered at the zoomed resolution once a gesture settles (never CSS-scaled
// into blur), with a cheap transform of the last sharp bitmap while it is in flight.
const clampV=(x,lo,hi)=>Math.max(lo,Math.min(hi,x));
const view={zoom:1,panX:0,panY:0};let shownView={zoom:1,panX:0,panY:0},settleV=0,vDrag=null,vPinch=null;const vPointers=new Map();
function viewCenter(){return [canvasSize/2+view.panX,canvasSize/2+view.panY]}
function maxZoomV(){return tree?clampV((40*tree.rings.length)/Math.max(80,canvasSize*.445*.945),4,20):4}
function labelAngleV(){const dx=canvasSize/2-viewCenter()[0],dy=canvasSize/2-viewCenter()[1];return Math.hypot(dx,dy)<canvasSize*.22?-Math.PI/2:Math.atan2(dy,dx)}
function clampPanV(){const m=canvasSize/2+canvasSize*.445*view.zoom-30;view.panX=clampV(view.panX,-m,m);view.panY=clampV(view.panY,-m,m)}
function applyView(){clampPanV();const k=view.zoom/shownView.zoom;cv.style.transform=`translate(${view.panX-shownView.panX*k}px,${view.panY-shownView.panY*k}px) scale(${k})`;syncZoomHud();clearTimeout(settleV);settleV=setTimeout(paint,90)}
function syncZoomHud(){const el=document.getElementById('zoom-level');if(el)el.textContent=view.zoom.toFixed(1)+'×';art.classList.toggle('zoomed',view.zoom>1.001)}
function zoomAtV(sx,sy,f){const z0=view.zoom,z1=clampV(z0*f,1,maxZoomV());if(z1===z0)return;const [cx,cy]=viewCenter(),k=z1/z0;view.panX=sx-canvasSize/2-(sx-cx)*k;view.panY=sy-canvasSize/2-(sy-cy)*k;view.zoom=z1;if(z1===1){view.panX=0;view.panY=0}applyView()}
function resetView(){view.zoom=1;view.panX=0;view.panY=0;applyView()}
function localXY(e){const r=cv.getBoundingClientRect();return [(e.clientX-r.left)*canvasSize/r.width,(e.clientY-r.top)*canvasSize/r.height]}
// Hit-test against the geometry the bitmap was drawn for, corrected for an in-flight gesture.
function bandAtV(e){if(!geo)return null;const [x,y]=localXY(e),k=shownView.zoom/view.zoom,cx=canvasSize/2+shownView.panX,cy=canvasSize/2+shownView.panY,[vcx,vcy]=viewCenter();return LivingTrees.detailedRingAt(geo,cx,cy,cx+(x-vcx)*k,cy+(y-vcy)*k)}
cv.addEventListener('wheel',e=>{e.preventDefault();const [x,y]=localXY(e);zoomAtV(x,y,Math.exp(-e.deltaY*(e.ctrlKey?0.01:0.0022)))},{passive:false});
cv.addEventListener('dblclick',e=>{e.preventDefault();const [x,y]=localXY(e);zoomAtV(x,y,1.9)});
cv.addEventListener('pointerdown',e=>{cv.setPointerCapture(e.pointerId);vPointers.set(e.pointerId,{x:e.clientX,y:e.clientY});if(vPointers.size===2){const [a,b]=[...vPointers.values()],r=cv.getBoundingClientRect(),sc=canvasSize/r.width;vPinch={d:Math.hypot(a.x-b.x,a.y-b.y),zoom:view.zoom,mx:((a.x+b.x)/2-r.left)*sc,my:((a.y+b.y)/2-r.top)*sc,panX:view.panX,panY:view.panY};vDrag=null}else if(vPointers.size===1)vDrag={x:e.clientX,y:e.clientY,panX:view.panX,panY:view.panY,moved:0}});
cv.addEventListener('pointermove',e=>{if(vPointers.has(e.pointerId))vPointers.set(e.pointerId,{x:e.clientX,y:e.clientY});if(vPinch&&vPointers.size>=2){const [a,b]=[...vPointers.values()],d=Math.hypot(a.x-b.x,a.y-b.y);if(!d)return;view.zoom=vPinch.zoom;view.panX=vPinch.panX;view.panY=vPinch.panY;zoomAtV(vPinch.mx,vPinch.my,d/vPinch.d);return}if(vDrag&&view.zoom>1){vDrag.moved=Math.max(vDrag.moved,Math.hypot(e.clientX-vDrag.x,e.clientY-vDrag.y));if(vDrag.moved>3){const sc=canvasSize/cv.getBoundingClientRect().width;view.panX=vDrag.panX+(e.clientX-vDrag.x)*sc;view.panY=vDrag.panY+(e.clientY-vDrag.y)*sc;applyView()}}});
cv.addEventListener('pointerup',e=>{const wasDrag=vDrag&&vDrag.moved>4;vPointers.delete(e.pointerId);if(vPointers.size<2)vPinch=null;if(!vPointers.size){if(vDrag&&!wasDrag){const b=bandAtV(e);if(b)selectYear(b.year)}vDrag=null}});
cv.addEventListener('pointercancel',e=>{vPointers.delete(e.pointerId);if(vPointers.size<2)vPinch=null;if(!vPointers.size)vDrag=null});
document.getElementById('zoom-hud').addEventListener('click',e=>{const b=e.target.closest('[data-z]');if(!b)return;const c=canvasSize/2;if(b.dataset.z==='in')zoomAtV(c,c,1.4);else if(b.dataset.z==='out')zoomAtV(c,c,1/1.4);else resetView()});
function renderYearTable(){document.getElementById('year-table-wrap').innerHTML=`<table class="year-table"><thead><tr><th>year</th><th>return</th><th>vol</th><th>max DD</th></tr></thead><tbody>${tree.rings.slice().reverse().map(r=>`<tr data-year="${r.year}"><td><button type="button" class="year-button" data-year="${r.year}">${r.year}${r.partial?'*':''}</button></td><td>${r.ret>=0?'+':''}${pct(r.ret)}</td><td>${pct(r.vol)}</td><td>${pct(r.max_dd)}</td></tr>`).join('')}</tbody></table>`}
function update(){const m=LivingTrees.metrics(tree,9999);if(!m)return;const family=TreeInsights.familyOf(insights,tree),from=encodeURIComponent(params.get('from')||'forest'),kinParams=arbParams();
  document.title=`${tree.name} — Money Tree Forest`;
  document.getElementById('title').textContent=tree.name;document.getElementById('title-sub').textContent=`${m.years} annual rings · ${tree.first_year}–${tree.last_year}`;
  document.getElementById('back').textContent=`← ${ctx.family!=='all'?TreeInsights.FAMILY_LABELS[ctx.family]:ctx.cls!=='all'?LivingTrees.CLASS_NAMES[ctx.cls]:'Forest'}`;
  document.getElementById('name').textContent=tree.name;
  const classline=document.getElementById('classline');classline.textContent=`${tree.id.toUpperCase()} · ${LivingTrees.CLASS_NAMES[tree.cls]} · ${TreeInsights.FAMILY_LABELS[family]} · ${tree.first_year}–${tree.last_year}`;classline.style.color=LivingTrees.CLASS_COLORS[tree.cls];
  document.getElementById('hero').innerHTML=`<span class="hero-num">${grow(m)}</span><span class="hero-label">accumulated growth over ${m.ageYears.toFixed(m.ageYears<10?1:0)} years</span>`;
  document.getElementById('facts').innerHTML=`<span>annualized growth</span><b>${signed(m.cagr)}</b><span>positive years</span><b>${Math.round(m.positive*100)}%</b><span>mean volatility</span><b>${pct(m.meanVol)}</b><span>worst drawdown</span><b>${pct(m.worst)}</b>`;
  document.getElementById('field-notes').innerHTML=TreeInsights.notes(tree).map(note=>`<p class="field-note">${note}</p>`).join('');
  document.getElementById('kin').innerHTML=TreeInsights.relatives(insights,tree).map(({tree:t})=>{const f=TreeInsights.familyOf(insights,t),u=new URLSearchParams(kinParams);u.set('from',from);u.set('labels',yearLabels?'show':'hide');return`<a class="kin-link" href="${treeHref(t.id,u)}"><b style="color:${LivingTrees.CLASS_COLORS[t.cls]}">${t.id.toUpperCase()}</b><span>${t.name}</span><i>${TreeInsights.FAMILY_LABELS[f]}</i></a>`}).join('');
  document.getElementById('scar-count').textContent=m.scars.length?m.scars.length:'';
  document.getElementById('scars').innerHTML=m.scars.length?m.scars.slice().reverse().map(s=>`<div class="scar"><b>${s.date||s.year}</b> · ${pct(s.depth)} drawdown<br>${s.peak_date?`from the ${s.peak_date} ${s.nested?'interim high':'peak'} · `:''}${s.r_year?`recovered ${s.r_date||s.r_year}`:'still unrecovered in visible data'}</div>`).join(''):'<p class="empty">No qualifying major scars yet.</p>';
  tickerEl.value=tree.id;setUrl();document.getElementById('back').href=backHref();hoverYear=null;selectedYear=null;ringReadout.textContent=ringText(null);cv.setAttribute('aria-label',`${tree.name}, ${tree.id.toUpperCase()}, interactive annual rings from ${tree.first_year} through ${tree.last_year}`);document.getElementById('freshness').textContent=`Prices through ${new Date(`${tree.data_through}T12:00:00Z`).toLocaleDateString(undefined,{year:'numeric',month:'short',day:'numeric',timeZone:'UTC'})}`;document.getElementById('basis').textContent=BASIS_COPY[tree.basis]||'';renderYearTable();paint();Immersive.refresh()}
function select(id){const found=trees.find(t=>t.id===id);tree=found||trees[0];view.zoom=1;view.panX=0;view.panY=0;const n=document.getElementById('id-notice');if(n){n.hidden=!!found;if(!found)n.textContent=`No tree with id “${id.toUpperCase()}” — showing ${tree.name} instead.`}update()}
function move(dir){const nav=navList(),i=nav.indexOf(tree);select(nav[(i+dir+nav.length)%nav.length].id)}
document.getElementById('prev').onclick=()=>move(-1);document.getElementById('next').onclick=()=>move(1);tickerEl.onchange=e=>select(e.target.value);paletteEl.onclick=e=>{const b=e.target.closest('[data-palette]');if(!b||b.dataset.palette===palette)return;palette=b.dataset.palette;syncPalette();setUrl();paint();Immersive.refresh()};labelsEl.onclick=e=>{const b=e.target.closest('[data-labels]');if(!b)return;const next=b.dataset.labels==='show';if(next===yearLabels)return;yearLabels=next;syncYearLabels();setUrl();paint();Immersive.refresh()};document.getElementById('download-poster').onclick=downloadPoster;document.getElementById('year-table-wrap').onclick=e=>{const b=e.target.closest('[data-year]');if(b)selectYear(+b.dataset.year)};window.addEventListener('resize',paint);window.addEventListener('keydown',e=>{if(Immersive.isOpen())return;   // the full-screen viewer owns the keyboard while it is up
  if(e.target===cv&&(e.key==='ArrowLeft'||e.key==='ArrowRight')){e.preventDefault();stepYear(e.key==='ArrowLeft'?-1:1);return}if(e.target===cv&&(e.key==='+'||e.key==='='||e.key==='-'||e.key==='_'||e.key==='0')){e.preventDefault();const c=canvasSize/2;if(e.key==='0')resetView();else zoomAtV(c,c,(e.key==='+'||e.key==='=')?1.4:1/1.4);return}if(e.target.tagName==='SELECT'||e.target.tagName==='INPUT'||e.target.tagName==='BUTTON')return;if(e.key==='ArrowLeft')move(-1);if(e.key==='ArrowRight')move(1);if(e.key==='Escape')location.href=backHref()});
// Full-screen viewer: shares the tree's palette/label/selection state, and
// reports back so the URL and the inline canvas stay in step.
Immersive.mount({state:()=>({tree,palette,yearLabels,selectedYear}),selectYear,onChange:()=>{setUrl();if(!Immersive.isOpen())cv.focus()}});
document.getElementById('immerse').onclick=()=>Immersive.open();
// Share: the URL already carries tree, palette and labels. Native share sheet where there is one, clipboard otherwise.
document.getElementById('copy-link').onclick=async e=>{const b=e.currentTarget,url=location.href,title=`${tree.name} · Money Tree Forest`;try{if(navigator.share&&matchMedia('(pointer:coarse)').matches){await navigator.share({title,url})}else{await navigator.clipboard.writeText(url);const old=b.textContent;b.textContent='Copied';setTimeout(()=>b.textContent=old,1400)}}catch(err){if(err&&err.name!=='AbortError')console.error(err)}};
cv.onmousemove=e=>{if(vDrag&&vDrag.moved>3)return;const b=bandAtV(e);if(!b){tip.style.opacity=0;if(hoverYear){hoverYear=null;updateRingReadout(selectedYear);paint()}return}if(hoverYear!==b.year){hoverYear=b.year;updateRingReadout(b.year);paint()}const ring=tree.rings.find(x=>x.year===b.year);tip.innerHTML=`<b>${tree.id.toUpperCase()} · ${b.year}${ring.partial?' (partial)':''}</b><br>return ${ring.ret>=0?'+':''}${pct(ring.ret)} · volatility ${pct(ring.vol)}<br>max drawdown ${pct(ring.max_dd)} · trough ${ring.scar_date||'—'}`;tip.style.left=Math.min(innerWidth-280,e.clientX+15)+'px';tip.style.top=Math.max(8,e.clientY+15)+'px';tip.style.opacity=1};cv.onmouseleave=()=>{tip.style.opacity=0;hoverYear=null;updateRingReadout(selectedYear);paint()};
LivingTrees.load('../data/rings.json').then(d=>{data=d;trees=d.trees.filter(t=>t.featured).map((t,i)=>Object.assign(t,{_i:i}));insights=TreeInsights.create(trees);seq=Collection.order(trees,insights,{sort:ctx.sort,cls:ctx.cls,family:ctx.family,q:ctx.q});tickerEl.innerHTML=trees.map(t=>`<option value="${t.id}">${t.id.toUpperCase()} · ${t.name}</option>`).join('');document.getElementById('back').href=backHref();syncPalette();syncYearLabels();select((params.get('id')||window.TREE_ROUTE||'btc').toLowerCase());if(params.get('view')==='full')Immersive.open()}).catch(error=>{console.error(error);document.querySelector('.toolbar').hidden=true;document.querySelector('.viewer').hidden=true;document.getElementById('load-error').hidden=false;});
